Repository MOVIEJOJO7/cat-talk, pull requests merged in 2023-11, with the labels that each got.

#9 Feat : 폴더 구조 및 PR 템플릿 업로드
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  hooks/.gitkeep
  type/.gitkeep
Labels: enhancement

#10 Feat : 모든 오픈 채팅방 목록 화면에 보여주기
  Components/Search/FilterOpenChat.tsx
  Components/Search/OpenChatPicture.tsx
  Components/Search/OpenChatText.tsx
  Components/Search/SearchOpenChat.tsx
  Components/Search/ShowAllOpenChat.tsx
  app/search/page.tsx
  app/search/search.type.ts
  app/search/search.utils.ts
Labels: enhancement

#14 Feat : 오픈 채팅방 목록 검색 세부 기능 추가
  Components/Search/SearchOpenChat.tsx
Labels: enhancement

#24 Feat : 환경변수 사용 X, 쿠키로 대체 pr
  Components/Open/ChatGenerator/ChatGenerator.tsx
  Components/Open/ChatGenerator/ChatGeneratorMenu/ChatGeneratorMenu.tsx
  Components/Open/ChatList/ChatList.tsx
  app/open/page.tsx
Labels: bug

#27 Feat : 오픈 채팅방 검색 페이지 디자인
  Components/Search/OpenChatPicture.tsx
  Components/Search/OpenChatText.tsx
  Components/Search/SearchOpenChat.tsx
  Components/Search/ShowAllOpenChat.tsx
  app/globals.css
  app/search/search.utils.ts
Labels: enhancement

#29 Feat : 회원가입 에러메세지 및 라우터
  Components/Join/JoinForm.tsx
  Components/Login/LoginForm.tsx
  app/join/page.tsx
  app/login/page.tsx
  package-lock.json
  package.json
  public/logo.png
Labels: enhancement

#31 Feat : 유저/채팅 검색 페이지 유저 디자인 변경
  Components/Search/OpenChatModal.tsx
  Components/Search/OpenChatPicture.tsx
  Components/Search/OpenChatText.tsx
  Components/Search/SearchOpenChat.tsx
  Components/Search/ShowAllOpenChat.tsx
  Components/Users/SearchUsers.tsx
  Components/Users/ShowSearchedFriend.tsx
  app/search/search.constant.ts
  app/search/search.type.ts
  app/search/search.utils.ts
  app/searchmychat/page.tsx
  hooks/Common/search.ts
  public/icon_back.svg
  public/icon_cancel.svg
  public/icon_cancel_normal.svg
Labels: enhancement

#32 Feat : 채팅방 드래그 드랍으로 구현 #19 pr
  Components/Open/ChatList/ChatItem.tsx
  Components/Open/ChatList/ChatItemDrag.tsx
  Components/Open/ChatList/ChatList.tsx
  Components/Open/ChatList/ChatList.type.ts
  app/open/open.type.ts
  app/open/page.tsx
  hooks/Open/useFetchPatchDeleteChat.ts
  package-lock.json
  package.json
  public/icon_trash.svg
  tailwind.config.ts
Labels: enhancement

#38 Fix: allOpenChat 타입 에러 해결
  Components/Search/OpenChatModal.tsx
  Components/Search/OpenChatText.tsx
  Components/Search/SearchOpenChat.tsx
  Components/Search/ShowAllOpenChat.tsx
  app/search/search.constant.ts
  app/search/search.type.ts
  app/search/search.utils.ts
  type/.gitkeep
  types/index.ts
Labels: bug

#42 Feat : 클라우디너리 연동
  Components/Join/DropZone/DropZone.tsx
  Components/Join/JoinForm.tsx
  Components/Search/OpenChatModal.tsx
  app/chat/[id]/page.tsx
  app/chatting/page.tsx
  hooks/Open/useCurrentSearchParmas.ts
  next.config.js
  package-lock.json
  package.json
  pages/api/image/post.ts
Labels: enhancement

#47 Feat : Private, Open tab으로 나누기, 캐시에 userId 추가
  Components/Common/Footer.tsx
  Components/Login/LoginForm.tsx
  Components/Open/ChatDivder/ChatDivder.tsx
  Components/Open/ChatGenerator/ChatGenerator.tsx
  Components/Open/ChatGenerator/ChatGeneratorMenu/ChatGeneratorMenu.tsx
  Components/Open/ChatList/ChatDraggable/ChatDraggable.tsx
  Components/Open/ChatList/ChatDroppable/ChatDroppableDelete.tsx
  Components/Open/ChatList/ChatDroppable/ChatDroppableList.tsx
  Components/Open/ChatList/ChatItem/ChatItem.tsx
  Components/Open/ChatList/ChatItem/ChatItemDrag.tsx
  Components/Open/ChatList/ChatList.tsx
  Components/Open/ChatList/ChatList.type.ts
  Components/Open/SpeedDial/SpeedDial.tsx
  app/chatting/chatting.type.ts
  app/chatting/chatting.utils.ts
  app/chatting/page.tsx
  app/open/open.constant.ts
Labels: enhancement

#52 Feat : 소켓으로 채팅방 구현 (지훈)
  Components/Chat/ChatRoom.tsx
  app/chat/[id]/page.tsx
Labels: enhancement

#54 Feat : 소켓으로 채팅방 구현
  Components/Chat/ChatHeader.tsx
  Components/Chat/Chats.tsx
  Components/Chat/RenderChats.tsx
  Components/Search/OpenChatModal.tsx
  types/index.ts
Labels: enhancement

#56 Fix : 빌드 오류 수정 pr
  Components/Users/ProfileModal.tsx
Labels: bug

#57 FIx: 채팅 빌드 에러 해결
  app/chat/[id]/page.tsx
Labels: bug

#58 Feat : 채팅방 Open, Private 분기 pr
  Components/Common/AsyncLoading/AsyncLoading.tsx
  Components/Common/AsyncLoading/AsyncSpinner.tsx
  Components/Common/Footer.tsx
  Components/Common/PageLoading/PageSpinner.tsx
  Components/Common/PageLoading/ProgressBar.tsx
  Components/Join/Join.types.ts
  Components/Join/JoinForm.tsx
  Components/Login/Login.types.ts
  Components/Login/LoginForm.tsx
  Components/Open/ChatDivder/ChatDivider.tsx
  Components/Open/ChatDivder/ChatDividerOpen.tsx
  Components/Open/ChatGenerator/ChatGenerator.tsx
  Components/Open/ChatGenerator/ChatGeneratorMenu/ChatGeneratorMenu.tsx
  Components/Open/ChatList/ChatDraggable/ChatDraggable.tsx
  Components/Open/ChatList/ChatDroppable/ChatDroppableDelete.tsx
  Components/Open/ChatList/ChatDroppable/ChatDroppableList.tsx
  Components/Open/ChatList/ChatItem/ChatItem.tsx
  Components/Open/ChatList/ChatList.tsx
  Components/Open/ChatList/ChatList.type.ts
  Components/Open/SpeedDial/SpeedDial.tsx
  Components/Wrapper.tsx
  app/layout.tsx
  app/loading.tsx
  app/open/page.tsx
  app/private/chatting.type.ts
  app/private/chatting.utils.ts
  app/private/page.tsx
  atoms/asyncLoadingAtom.ts
  hooks/Open/useAsyncLoading.ts
  hooks/Open/useFetchPostNewChat.ts
  package-lock.json
  package.json
  public/icon_footer_cat.svg
  public/icon_footer_open.svg
  public/icon_footer_private.svg
  public/icon_footer_search.svg
  tailwind.config.ts
Labels: enhancement

#64 Feat: 채팅방 사용자 입장 및 나가기 기능 추가
  Components/Chat/ChatRoom.tsx
  Components/Chat/RenderChats.tsx
  Components/Search/OpenChatModal.tsx
  app/error.tsx
  app/not-found.tsx
Labels: bug, enhancement

#65 Fix : JoinPage DropZone 위치, 모양 변경 + 추가 (Login Page 일부 수정)
  Components/Join/DropZone/DropZone.tsx
  Components/Join/JoinForm.tsx
  Components/Login/LoginForm.tsx
  public/icon_camera.svg
  tailwind.config.ts
Labels: bug, enhancement

#70 Feat : Private, Public 채팅방 정렬 순서 변경
  Components/Open/ChatList/ChatItem/ChatItem.tsx
  app/private/chatting.type.ts
  app/private/chatting.utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
  utils/changeKoreanTime.tsx
Labels: bug, enhancement

#72 Feat : 로그인, 회원가입 페이지 디자인
  Components/Join/DropZone/DropZone.tsx
  Components/Join/JoinForm.tsx
  Components/Login/LoginForm.tsx
  app/join/page.tsx
  app/login/page.tsx
  public/icon_dot_chat.svg
  public/icon_dot_multi_chat.svg
  public/icon_foot.svg
  tailwind.config.ts
Labels: enhancement

#78 Feat: 채팅방 디자인 작업 enhancement
  Components/Chat/ChatHeader.tsx
  Components/Chat/ChatRoom.tsx
  Components/Chat/Chats.tsx
  Components/Chat/RenderChats.tsx
  Components/Wrapper.tsx
  public/icon_back 2.svg
  public/icon_back.svg
  public/icon_exit.svg
  public/icon_send.svg
  public/icon_user.svg
Labels: enhancement

#80 Fix: Socket 이전메시지 버그 해결
  Components/Chat/ChatRoom.tsx
Labels: bug

#85 Feat: 채팅방 디자인 수정 및 기능 추가
  Components/Chat/ChatHeader.tsx
  Components/Chat/ChatRoom.tsx
  Components/Chat/Chats.tsx
  Components/Chat/RenderChats.tsx
  tailwind.config.ts
Labels: enhancement

#90 Feat : Header, User Search 외 디자인 변경사항들 수정
  Components/Common/AsyncLoading/AsyncLoading.tsx
  Components/Common/Button.tsx
  Components/Common/Footer.tsx
  Components/Common/Header.tsx
  Components/Common/Wrapper.tsx
  Components/Join/DropZone/DropZone.tsx
  Components/Open/ChatDivder/ChatDivider.tsx
  Components/Open/ChatDivder/ChatDividerOpen.tsx
  Components/Open/ChatGenerator/ChatGenerator.tsx
  Components/Open/ChatGenerator/ChatGeneratorMenu/ChatGeneratorMenu.tsx
  Components/Open/ChatList/ChatItem/ChatItem.tsx
  Components/Open/ChatList/ChatList.tsx
  Components/Open/SpeedDial/SpeedDial.tsx
  Components/Search/OpenChatModal.tsx
  Components/Search/OpenChatText.tsx
  Components/Search/SearchOpenChat.tsx
  Components/Search/ShowAllOpenChat.tsx
  Components/Users/FriendProfiles.tsx
  Components/Users/SearchUsers.tsx
  Components/Users/ShowSearchedFriend.tsx
  app/home/page.tsx
  app/join/page.tsx
  app/layout.tsx
  app/open/page.tsx
  app/private/page.tsx
  app/search/page.tsx
  hooks/Open/useFetchPatchDeleteChat.ts
  hooks/Open/useFetchPostNewChat.ts
  next.config.js
Labels: bug, enhancement

#92 Feat : 불필요한 라이브러리 삭제, 리다이렉트 수정
  app/home/page.tsx
  next.config.js
  package-lock.json
  package.json
Labels: bug

#94 Feat: README.md 1차 작성
  README.md
Labels: enhancement

#96 Feat : Hotfix
  Components/Common/Footer.tsx
  Components/Login/LoginForm.tsx
  app/loading.tsx
  app/users/page.tsx
  public/icon_cat_words.svg
Labels: bug

#107 Fix: 채팅 들어가과 나가기 에러 해결
  Components/Chat/ChatRoom.tsx
Labels: bug

#109 Fix: 오픈 채팅방 이미지 깨지는 문제 해결
  Components/Search/OpenChatModal.tsx
Labels: bug

#115 Feat: README.md 업데이트
  README.md
Labels: enhancement

#121 Feat: 소켓 연결 로직 개선
  Components/Chat/ChatRoom.tsx
  app/chat/[id]/page.tsx
Labels: bug, enhancement
